name: Slack Notifications for SnakeOps

on:
  push:
    branches:
      - main
      - develop

jobs:
  slack-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 A push was made to *${{ github.ref_name }}* by *${{ github.actor }}*.\n💬 Commit message: `${{ github.event.head_commit.message }}`\n🔗 <${{ github.event.head_commit.url }}|View Commit>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

